# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: zweck
email: phil@zweck.co
description: > # this means to ignore newlines until "baseurl:"
  This is the blog and website for zweck ltd.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zweck.co" # the base hostname & protocol for your site
twitter_username: zweck_co
github_username:  zweck

# Build settings
markdown: kramdown
